### PR TITLE
componentType instead of component in MultiInstantiate

### PR DESCRIPTION
**Pull request by dokato**
I found a bug in my recent update. There should be attribute `componentType` instead of `component` in MultiInstantiate.

### CODE REVIEW

**Comment by dokato** [comment]
@pgleeson according to our talk I added to  MultiInstantiate init both `component` and `componentType`.

**Comment by pgleeson** [comment]
@dokato MultiInstantiate should contain either an attribute component or an attribute component_type, not both. You should update the constructor to reflect this, as well as the export to xml, to check which of component or component_type is not None. 

Note: make sure the instantiation at https://github.com/LEMS/pylems/blob/master/lems/model/model.py#L705 uses the correct form of constructor. This is what's failing at present. Try running the included examples before committing to make sure it works correctly.

**Comment by dokato** [comment]
Ok, now should be fine.

**Comment by pgleeson** [comment]
@dokato merged now.

**Pull request merged**
